<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Version>$(ImportContractVersion)</Version>
    <AssemblyVersion>$(ImportContractVersion)</AssemblyVersion>
    <FileVersion>$(ImportContractVersion)</FileVersion>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <WarningsAsErrors>CS1591</WarningsAsErrors>
  </PropertyGroup>

</Project>
