<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <WarningsAsErrors>CS1591</WarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <Using Include="Microsoft.Extensions.Logging" />
    <ProjectReference Include="..\Rezepte.Import.Abstractions\Rezepte.Import.Abstractions.csproj" />
    <PackageReference Include="Google.Cloud.Vision.V1" Version="3.8.0" />
    <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.9" />
  </ItemGroup>
  <ItemGroup Condition="'$(RezepteWebReferencePath)' != ''">
    <Reference Include="Rezepte.Web">
      <HintPath>$(RezepteWebReferencePath)</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup Condition="'$(RezepteWebReferencePath)' == ''">
    <Reference Include="Rezepte.Web">
      <HintPath>..\Rezepte.Web\bin\$(Configuration)\$(TargetFramework)\Rezepte.Web.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
