// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Rezepte.Web.Data;

#nullable disable

namespace Rezepte.Web.Migrations
{
    [DbContext(typeof(RezepteDbContext))]
    [Migration("20260706090000_AddBackgroundJobsTable")]
    partial class AddBackgroundJobsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");
#pragma warning restore 612, 618
        }
    }
}
